const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

exports.generatePDF = async (investigation) => {
  return new Promise((resolve, reject) => {
    try {
      // Create temp directory if it doesn't exist
      const tempDir = path.join(__dirname, "../temp");
      if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
      }

      const fileName = `investigation_${investigation._id}_${Date.now()}.pdf`;
      const filePath = path.join(tempDir, fileName);
      
      const doc = new PDFDocument();
      const stream = fs.createWriteStream(filePath);
      
      doc.pipe(stream);

      // Header
      doc.fontSize(20).text("Illegal Fishing Investigation Report", {
        align: "center"
      });
      doc.moveDown();
      doc.moveDown();

      // Report Information
      doc.fontSize(14).text("REPORT DETAILS", { underline: true });
      doc.moveDown();
      doc.fontSize(10);
      
      if (investigation.reportId) {
        doc.text(`Report ID: ${investigation.reportId._id || investigation.reportId}`);
        doc.text(`Date Filed: ${investigation.reportId.createdAt ? new Date(investigation.reportId.createdAt).toLocaleDateString() : 'N/A'}`);
        doc.text(`Location: ${investigation.reportId.location || 'N/A'}`);
        doc.text(`District: ${investigation.reportId.district || 'N/A'}`);
        doc.text(`Original Description: ${investigation.reportId.description || 'N/A'}`);
      } else {
        doc.text(`Report ID: ${investigation.reportId}`);
      }
      doc.moveDown();
      doc.moveDown();

      // Investigation Details
      doc.fontSize(14).text("INVESTIGATION DETAILS", { underline: true });
      doc.moveDown();
      doc.fontSize(10);
      doc.text(`Officer: ${investigation.officerId?.name || 'N/A'}`);
      doc.text(`Officer Email: ${investigation.officerId?.email || 'N/A'}`);
      doc.text(`Officer District: ${investigation.officerId?.district || 'N/A'}`);
      doc.text(`Visit Date: ${new Date(investigation.visitDate).toLocaleDateString()} at ${investigation.visitTime}`);
      doc.text(`Visited Location: ${investigation.visited ? "Yes" : "No"}`);
      doc.text(`Illegal Activity Found: ${investigation.illegalActivityFound ? "Yes" : "No"}`);
      doc.moveDown();
      doc.moveDown();

      // Findings
      doc.fontSize(14).text("FINDINGS", { underline: true });
      doc.moveDown();
      doc.fontSize(10);
      doc.text(`Actual Situation Observed:`, { continued: true });
      doc.text(` ${investigation.actualSituation || 'N/A'}`);
      doc.moveDown();
      doc.moveDown();

      // Action Taken
      doc.fontSize(14).text("ACTION TAKEN", { underline: true });
      doc.moveDown();
      doc.fontSize(10);
      doc.text(`Action: ${investigation.actionTaken?.replace(/_/g, ' ') || 'N/A'}`);
      
      if (investigation.actionDescription) {
        doc.text(`Description: ${investigation.actionDescription}`);
      }
      
      if (investigation.fineAmount && investigation.fineAmount > 0) {
        doc.text(`Fine Amount: LKR ${investigation.fineAmount.toLocaleString()}`);
      }
      doc.moveDown();
      doc.moveDown();

      // Officer Notes
      if (investigation.officerNotes) {
        doc.fontSize(14).text("OFFICER NOTES", { underline: true });
        doc.moveDown();
        doc.fontSize(10);
        doc.text(investigation.officerNotes);
        doc.moveDown();
        doc.moveDown();
      }

      // Evidence Summary
      if (investigation.evidenceImages && investigation.evidenceImages.length > 0) {
        doc.fontSize(14).text("EVIDENCE", { underline: true });
        doc.moveDown();
        doc.fontSize(10);
        doc.text(`Images uploaded: ${investigation.evidenceImages.length}`);
        investigation.evidenceImages.forEach((img, i) => {
          doc.text(`  - Image ${i + 1}: ${path.basename(img)}`);
        });
      }
      
      if (investigation.evidenceVideos && investigation.evidenceVideos.length > 0) {
        doc.text(`Videos uploaded: ${investigation.evidenceVideos.length}`);
        investigation.evidenceVideos.forEach((video, i) => {
          doc.text(`  - Video ${i + 1}: ${path.basename(video)}`);
        });
      }
      doc.moveDown();
      doc.moveDown();

      // Status
      doc.fontSize(14).text("RESOLUTION STATUS", { underline: true });
      doc.moveDown();
      doc.fontSize(10);
      doc.text(`Investigation Status: ${investigation.status || 'N/A'}`);
      if (investigation.resolvedAt) {
        doc.text(`Resolved At: ${new Date(investigation.resolvedAt).toLocaleString()}`);
      }
      
      // Footer
      doc.moveDown(2);
      doc.fontSize(8).text("This is an official report generated by the Illegal Fishing Monitoring System", {
        align: "center"
      });
      doc.fontSize(8).text(`Generated on: ${new Date().toLocaleString()}`, {
        align: "center"
      });

      doc.end();

      stream.on("finish", () => {
        console.log(`PDF generated successfully: ${filePath}`);
        resolve(filePath);
      });

      stream.on("error", (error) => {
        console.error("Stream error:", error);
        reject(error);
      });

    } catch (error) {
      console.error("PDF generation error:", error);
      reject(error);
    }
  });
};